#!/usr/bin/env tsx
/**
 * dump-schema.ts — Snapshot des Live-Schemas (Tables, Columns, Indexes,
 * Constraints, Policies) in eine Markdown-Datei.
 *
 * Audit 2026-05-11: das Repo enthält keine vollständige Schema-Baseline
 * (supabase/migrations/0000_initial_schema.sql ist leer). Diese Skript
 * läuft gegen die LIVE-Supabase und schreibt das aktuelle Schema raus,
 * damit (a) PR-Reviews Schema-Änderungen sehen, (b) ein Snapshot vor
 * RLS-Migration 0011 möglich ist.
 *
 * NICHT in Production-Runtime einbinden — read-only Diagnose-Tool.
 *
 * Usage:
 *   npx tsx scripts/dump-schema.ts > supabase/schema-snapshot.md
 *
 * Benötigt Env: NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY.
 */
import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'

const url = process.env.NEXT_PUBLIC_SUPABASE_URL
const key = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient(url, key)

// Wir nutzen das Postgres `information_schema` + `pg_catalog` über einen
// hand-gemachten RPC. Falls der RPC nicht existiert: User kriegt eine
// klare Fehlermeldung und ein SQL-Snippet, das er einmal in Supabase-SQL-
// Editor laufen lassen soll.
const RPC_NAME = 'admin_schema_snapshot'
const RPC_SQL = `
CREATE OR REPLACE FUNCTION public.admin_schema_snapshot()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, information_schema, pg_catalog
AS $$
SELECT jsonb_build_object(
  'tables', (
    SELECT jsonb_agg(jsonb_build_object(
      'table_name', table_name,
      'columns', (
        SELECT jsonb_agg(jsonb_build_object(
          'name', column_name,
          'type', data_type,
          'nullable', is_nullable = 'YES',
          'default', column_default
        ) ORDER BY ordinal_position)
        FROM information_schema.columns c
        WHERE c.table_schema = 'public' AND c.table_name = t.table_name
      )
    ) ORDER BY table_name)
    FROM information_schema.tables t
    WHERE t.table_schema = 'public' AND t.table_type = 'BASE TABLE'
  ),
  'indexes', (
    SELECT jsonb_agg(jsonb_build_object(
      'table', tablename,
      'index', indexname,
      'def', indexdef
    ) ORDER BY tablename, indexname)
    FROM pg_indexes WHERE schemaname = 'public'
  ),
  'policies', (
    SELECT jsonb_agg(jsonb_build_object(
      'table', tablename,
      'policy', policyname,
      'cmd', cmd,
      'permissive', permissive,
      'roles', roles,
      'using', qual,
      'with_check', with_check
    ) ORDER BY tablename, policyname)
    FROM pg_policies WHERE schemaname = 'public'
  ),
  'rls_status', (
    SELECT jsonb_object_agg(tablename, rowsecurity ORDER BY tablename)
    FROM pg_tables WHERE schemaname = 'public'
  ),
  'foreign_keys', (
    SELECT jsonb_agg(jsonb_build_object(
      'table', tc.table_name,
      'column', kcu.column_name,
      'references_table', ccu.table_name,
      'references_column', ccu.column_name,
      'on_delete', rc.delete_rule,
      'on_update', rc.update_rule
    ) ORDER BY tc.table_name, kcu.column_name)
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage ccu
      ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
    JOIN information_schema.referential_constraints rc
      ON rc.constraint_name = tc.constraint_name AND rc.constraint_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
  )
)
$$;
REVOKE ALL ON FUNCTION public.admin_schema_snapshot() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_schema_snapshot() TO service_role;
`

async function main() {
  const { data, error } = await supabase.rpc(RPC_NAME)
  if (error) {
    console.error(`[dump-schema] RPC ${RPC_NAME} fehlt oder failed: ${error.message}`)
    console.error('\nLäuft dies einmalig im Supabase-SQL-Editor:\n')
    console.error(RPC_SQL)
    process.exit(2)
  }

  const snap = data as Record<string, unknown>
  console.log(`# Schema-Snapshot — ${new Date().toISOString()}\n`)
  console.log(`Generated by \`scripts/dump-schema.ts\`. Source: live Supabase via \`${RPC_NAME}\` RPC.\n`)

  console.log('## RLS Status\n')
  console.log('| Tabelle | RLS aktiv |')
  console.log('|---|---|')
  const rls = snap.rls_status as Record<string, boolean>
  for (const [t, on] of Object.entries(rls).sort(([a], [b]) => a.localeCompare(b))) {
    console.log(`| ${t} | ${on ? '✅' : '❌'} |`)
  }

  console.log('\n## Tables\n')
  const tables = snap.tables as Array<{ table_name: string; columns: Array<{ name: string; type: string; nullable: boolean; default: string | null }> }>
  for (const t of tables) {
    console.log(`\n### \`${t.table_name}\`\n`)
    console.log('| Spalte | Typ | NULL | Default |')
    console.log('|---|---|---|---|')
    for (const c of t.columns) {
      console.log(`| ${c.name} | ${c.type} | ${c.nullable ? '✅' : '❌'} | ${c.default ?? ''} |`)
    }
  }

  console.log('\n## Foreign Keys\n')
  const fks = snap.foreign_keys as Array<{ table: string; column: string; references_table: string; references_column: string; on_delete: string; on_update: string }>
  console.log('| Tabelle | Spalte | → Referenz | ON DELETE | ON UPDATE |')
  console.log('|---|---|---|---|---|')
  for (const fk of fks ?? []) {
    console.log(`| ${fk.table} | ${fk.column} | ${fk.references_table}.${fk.references_column} | ${fk.on_delete} | ${fk.on_update} |`)
  }

  console.log('\n## Indexes\n')
  const indexes = snap.indexes as Array<{ table: string; index: string; def: string }>
  console.log('| Tabelle | Index | Definition |')
  console.log('|---|---|---|')
  for (const i of indexes ?? []) {
    console.log(`| ${i.table} | ${i.index} | \`${i.def.replace(/\|/g, '\\|')}\` |`)
  }

  console.log('\n## Policies\n')
  const policies = snap.policies as Array<{ table: string; policy: string; cmd: string; roles: string[]; using: string; with_check: string }>
  if (!policies || policies.length === 0) {
    console.log('_Keine Policies definiert — RLS-Migration 0011 fehlt._')
  } else {
    console.log('| Tabelle | Policy | CMD | Roles | USING | WITH CHECK |')
    console.log('|---|---|---|---|---|---|')
    for (const p of policies) {
      console.log(`| ${p.table} | ${p.policy} | ${p.cmd} | ${(p.roles ?? []).join(',')} | \`${(p.using ?? '').replace(/\|/g, '\\|')}\` | \`${(p.with_check ?? '').replace(/\|/g, '\\|')}\` |`)
    }
  }
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
